### ISSUE TITLE
Missing statements/read/mine scope

### ISSUE THREAD

**Issue by DmitriyKabanov** [yetanalytics/lrsql#233]
I wonder why LRSQL is missing `statements/read/mine` scope. 
It's critical for us to separate xapi access by customer.
Is there any other way we can achieve this behaviour?

**Comment by kelvinqian00** [comment]
Hello @DmitriyKabanov!

We did not implement `statements/read/mine` in SQL LRS since at that time none of our LRS customers has had a need for that feature, so we decided to deprioritize it during development. Now that we have people like you who do have a need, implementing it is back on our roadmap.

Are you using the recently-added OIDC authentication for SQL LRS? We are curious if the `statements/read/mine` scope would be more popular now that we have added support for OIDC.

**Comment by DmitriyKabanov** [comment]
Hi @kelvinqian00!

No, we're using api key/secret pairs per customer.

1. Do you have a timeline when this feature will be implemented?
2. Could you please confirm, that we can continue using LRS SQL with api key/secret pairs and assume that access control via `statements/read/mine` will just work as soon as you release it?

**Comment by DmitriyKabanov** [comment]
Hey @milt! 

It's been a while since out last catchup.
Is there any updates?

**Comment by kelvinqian00** [comment]
We currently have a PR up that will implement this feature (#245). However, as Milt said previously we are also busy with several other projects at the moment, so it may be a while before the update is officially released.

**Comment by DmitriyKabanov** [comment]
Hey @kelvinqian00! 

Thank you for the update.
Do you have an ETA when this PR will go live?
It's been a month this PR is open.

**Comment by kelvinqian00** [comment]
Our team is currently working on releasing an open beta for a separate project, and we are aiming to release that either end of this week or beginning of next week. Once that is done we can refocus and return to SQL LRS tasks such as this.

**Comment by kelvinqian00** [comment]
Apologies for the delay, but the `statements/read/mine` scope has been implemented in the latest release of SQL LRS [v0.3.6](https://github.com/yetanalytics/lrsql/releases/tag/v0.3.6).

**Comment by kelvinqian00** [comment]
Closed as the `statements/read/mine` scope feature has been implemented with no issue for over a month.
