### ISSUE TITLE
SQL Idl Connection

### ISSUE THREAD

**Issue by brunoMaurice** [yetanalytics/lrsql#243]
Hi,

We have a very strange behaviour with lrsql since few week we experiment an over use of database connection that stay in idle state. At the same moment we have growing usage of connection the CPU same to be very active.

![Screenshot 2022-08-09 at 12 02 01](https://user-images.githubusercontent.com/2838998/183625124-740ba559-4722-4245-80c7-6b46a9debc32.png)

This situation is very strange because the instance running the lrsql dont get any request from is domain name. Its like doing something by himself (maybe a cron or something like that).

Any idea of what could cause this situation ?

Docker version : yetanalytics/lrsql:v0.3.3
Run on Cloud run instance
Database on Cloud Sql : PostgreSql 13

**Comment by brunoMaurice** [comment]
A little up to get some info.

We continue to have a huge usage of database connection not release by the lrsql. 
For each instance we have 10 connection use and keep in idle status.

**Comment by kelvinqian00** [comment]
Hello @brunoMaurice, apologies for the delay.

> For each instance we have 10 connection use and keep in idle status.

This is because SQL LRS operates on top of a connection pool, and in the [configuration](https://github.com/yetanalytics/lrsql/blob/main/doc/env_vars.md#hikaricp-properties) we set the value of `poolMinimumIdle` to `10` (in Postgres) in order to ensure a fixed-size connection pool. In other words,  This is recommended by [HikariCP](https://github.com/brettwooldridge/HikariCP) (the connection pool library we are using) for performance reasons, but you can try lowering `poolMinimumIdle` to see if that helps in your use case.

**Comment by brunoMaurice** [comment]
Great we will try to update the env variable following the database configuration. Thanks.
