### ISSUE TITLE
Installation Pre-Requisites

### ISSUE THREAD

**Issue by jsmith325** [yetanalytics/lrsql#445]
Hello!  I am attempting to install SQLRS and am running into an issue that I'm sure is my own fault.

I have a fresh, updated install of Ubuntu 22.04 (jammy) running on a VM inside VMware ESXi.

I'm following the Getting Started Doc here: https://github.com/yetanalytics/lrsql/blob/main/doc/startup.md

After configuring the sqlrs.json file with my variables, I attempt to run the sqlite install but keep running into the same error:

> [main] ERROR com.zaxxer.hikari.pool.HikariPool - my-pool-name - Exception during pool initialization.
java.sql.SQLException: path to '//0.0.0.0:5432/lrsql_db': '/0.0.0.0:5432' does not exist

I installed both MySQL server and Java, but still get this error.

Do I need to create the database first, then run bin/run_sqlite.sh?

Are there other pre-requisites to SQLRS that need to be set up on my system before following the directions on the Getting Started doc?

I appreciate any help.

**Comment by kelvinqian00** [comment]
Hello @jsmith325, 

Thanks for creating this issue. First of all, SQL LRS currently does not support MySQL, only SQLite and PostgreSQL, but since you're trying to run the SQLite version that doesn't matter either way. In fact, with SQLite you should not have to create or connect to any databases.

That said, it may be possible that you are accidentally trying to run the PostgreSQL version of SQL LRS. The fact that the application is attempting to connect to a database at port `5432` (the default port for PostgreSQL) suggests this. What script are you using to run SQL LRS?

In addition, what are the values of your configuration variables? I should note that lrsql/config.json, not sqlrs.json, is the path of the configuration file specified by the Getting Started guide.
